package DistributedClassManagementSystem;

import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
* DistributedClassManagementSystem/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedClassManagementSystem.idl
* Thursday, June 14, 2018 10:27:13 o'clock PM EDT
*/
@WebService
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CenterServer 
{
	  boolean createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerId);
	  boolean createSRecord (String firstName, String lastName, String[] courseRegistered, String status, String statusDate, String managerId);
	  String getRecordCount (String managerId);
	  boolean editRecords (String recordId, String fieldName, String newValue, String managerId);
	  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
	
} // interface CenterServer
