package DistributedClassManagementSystem;


/**
* DistributedClassManagementSystem/CenterServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedClassManagementSystem.idl
* Tuesday, June 12, 2018 2:17:35 PM EDT
*/

public interface CenterServerOperations 
{
  boolean createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerId);
  boolean createSRecord (String firstName, String lastName, String[] courseRegistered, String status, String statusDate, String managerId);
  String getRecordCount (String managerId);
  boolean editRecords (String recordId, String fieldName, String newValue, String managerId);
} // interface CenterServerOperations
