package DistributedClassManagementSystem;


/**
* DistributedClassManagementSystem/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedClassManagementSystem.idl
* Thursday, June 14, 2018 8:57:26 o'clock PM EDT
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
