package DistributedClassManagementSystem;


/**
* DistributedClassManagementSystem/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedClassManagementSystem.idl
* Tuesday, June 12, 2018 2:17:35 PM EDT
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
