package FrontEndApp;


/**
* FrontEndApp/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Thursday, July 19, 2018 7:47:26 o'clock PM EDT
*/

public interface FrontEndOperations 
{
  String createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerId);
  String createSRecord (String firstName, String lastName, String[] courseRegistered, String status, String statusDate, String managerId);
  String getRecordCount (String managerId);
  String editRecords (String recordId, String fieldName, String newValue, String managerId);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface FrontEndOperations
